server.port=8084
spring.profiles.active=dev

# Shared settings
spring.web.resources.add-mappings=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}
app.cookie.secure=true

# Flyway
spring.sql.init.mode=always