server.port=8084

spring.profiles.active=dev

# Profile-independent settings
spring.web.resources.add-mappings=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT & Security
jwt.secret=Hd9T9G4ZkpeP7ELGRVUdXEs8NFu12u0aVxhpCVE+Kto=
jwt.expiration=900000
jwt.refresh-expiration=604800000
app.cookie.secure=true

# Flyway or SQL Init (Shared)
spring.sql.init.mode=always