
-- USERS
CREATE TABLE users (
 id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email    VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role     VARCHAR(20)  NOT NULL CHECK (role IN ('CLIENT', 'EMPLOYEE', 'ADMIN'))
);

-- CLIENT PROFILES
CREATE TABLE client_profiles (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT         NOT NULL UNIQUE,
  name    VARCHAR(255)   NOT NULL,
  balance DECIMAL(19, 2) NOT NULL,
  CONSTRAINT fk_client_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- EMPLOYEE PROFILES
CREATE TABLE employee_profiles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  name       VARCHAR(255),
  phone      VARCHAR(50),
  birth_date DATE,
  CONSTRAINT fk_employee_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- BOOKS
CREATE TABLE books (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(255)   NOT NULL UNIQUE,
  genre            VARCHAR(100),
  age_group        VARCHAR(20)    CHECK (age_group IN ('CHILD', 'TEEN', 'ADULT', 'OTHER')),
  price            DECIMAL(19, 2),
  publication_year DATE,
  author           VARCHAR(255),
  number_of_pages  INTEGER,
  stock            INTEGER,
  characteristics  VARCHAR(500),
  description      TEXT,
  language         VARCHAR(20)    CHECK (language IN ('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'UKRAINIAN', 'OTHER'))
    );

-- ORDERS
CREATE TABLE orders (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id  BIGINT         NOT NULL,
  order_date TIMESTAMP,
  price      DECIMAL(19, 2),
  CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES client_profiles (id) ON DELETE RESTRICT
);

-- BOOK ITEMS
CREATE TABLE book_items (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT  NOT NULL,
  book_id  BIGINT  NOT NULL,
  quantity INTEGER NOT NULL,
  CONSTRAINT fk_book_item_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_book_item_book  FOREIGN KEY (book_id)  REFERENCES books (id)  ON DELETE RESTRICT
);